# Generated by Django 4.2.5 on 2023-10-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
